name: main-ci
on: [push, pull_request]

jobs:

  build:
    name: Build-Test-Publish
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Build & Publish
      run: |
        dotnet build -c Release
        scripts/publish_src.sh

    - name: Test
      run: dotnet test --no-build --nologo -c Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: build/publish
